// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 10/7/2025, 2:49:58 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/Users/erencankanmaz/Documents/strong-pass/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/erencankanmaz/Documents/strong-pass/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/erencankanmaz/Documents/strong-pass/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/erencankanmaz/Documents/strong-pass/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/erencankanmaz/Documents/strong-pass/plugins/**/*.{js,ts,mjs}","/Users/erencankanmaz/Documents/strong-pass/composables/**/*.{js,ts,mjs}","/Users/erencankanmaz/Documents/strong-pass/utils/**/*.{js,ts,mjs}","/Users/erencankanmaz/Documents/strong-pass/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/erencankanmaz/Documents/strong-pass/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/erencankanmaz/Documents/strong-pass/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/erencankanmaz/Documents/strong-pass/app.config.{js,ts,mjs}","/Users/erencankanmaz/Documents/strong-pass/app/spa-loading-template.html"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;